import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import "react-datepicker/dist/react-datepicker.css";
import SideBar from "@/components/Common/SideBar";
import IndexWrapper from "@/Providers/IndexWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[1280px] mx-auto flex relative">
        <div className="min-w-[220px] max-w-[220px] h-screen border-r-[1px] border sticky top-0">
          <SideBar />
        </div>
        <div className="grow relative">
          <div className="min-h-screen smXYPadding bg-foreground">
            <IndexWrapper>{children}</IndexWrapper>
          </div>
        </div>
      </body>
    </html>
  );
}
