import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import "react-datepicker/dist/react-datepicker.css";
import SideBar from "@/components/Common/SideBar";
import IndexWrapper from "@/Providers/IndexWrapper";
import NavBar from "@/components/Common/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="w-full max-w-[1280px] mx-auto flex relative">
          <div className="hidden md:block md:min-w-[180px] md:max-w-[180px] xl:min-w-[220px] xl:max-w-[220px] h-screen border-r-[1px] border sticky top-0">
            <SideBar />
          </div>
          <div className="grow relative">
            <NavBar />
            <div className="w-full min-h-screen smXYPadding bg-foreground">
              <IndexWrapper>{children}</IndexWrapper>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
