import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import "react-datepicker/dist/react-datepicker.css";
import SideBar from "@/components/Common/SideBar";
import IndexWrapper from "@/Providers/IndexWrapper";
import NavBar from "@/components/Common/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <IndexWrapper>
          <div className="w-full max-w-[1280px] mx-auto flex relative">
            <div>
              <SideBar />
            </div>
            <div className="grow relative">
              <NavBar />
              <div className="w-full min-h-screen smXYPadding bg-foreground">
                {children}
              </div>
            </div>
          </div>
        </IndexWrapper>
      </body>
    </html>
  );
}
